# Site settings
title: Matthew J. Simoneau's Weblog
email: simoneau@gmail.com
description: > 
  Matthew Simoneau is a software developer in Boston, MA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.matthewsim.com" # the base hostname & protocol for your site
twitter_username: matthewsim
github_username:  simoneau

# Build settings
markdown: kramdown

